### ISSUE TITLE
[C2] Include optional tracking of users of a course who are not subscribed

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5958]
In the general (first) course reporting page, you can see results of users that are subscribed to the course.
If a course is "open" but users have entered without registering as students to the course, they are generating data in the tracking tables (database), but will not appear on the reporting pages because it first checks users registered in the course.

Add a button to the reporting page "Show users not registered". When clicking that button, the query changes to include all results (from registered and non-registered users) on the reporting page.

**Comment by christianbeeznest** [comment]
It is implemented with this commit https://github.com/chamilo/chamilo-lms/pull/6237/commits/fcef97597869170faebe8c73a7ee516b9ff6388c

Thanks for confirmation.

**Comment by klineur-M** [comment]
@ywarnier : 

- [X] create a new user in a existing course
- [X] check whether this course is "open" ( NOT only visible to the platform's regsitered users ; if not, change status to "open"
- [X] log out as admin
- [ ] log in as [[ new user ]] , explore the available courses , go for a visit ( NOT registration to the course )

>>> the only option is to register, not to visit the course.

Testing aborted.

**Comment by ywarnier** [comment]
@christianbeeznest I can see where you put that, but that is not where I was asking for it. I need that button in the *course reporting* page. When you enter a course and go to "Reporting" (e.g. https://testing25.beeznest.com/main/tracking/courseLog.php?cid=3&gid=0)

At the bottom of that page, there is a table that shows only the users subscribed to the course. I need a button to also show the users not subscribed. The current report you have made has to change (I would remove it completely from there). Sorry for the lack of precision in my initial request.

**Comment by christianbeeznest** [comment]
> [@christianbeeznest](https://github.com/christianbeeznest) I can see where you put that, but that is not where I was asking for it. I need that button in the _course reporting_ page. When you enter a course and go to "Reporting" (e.g. https://testing25.beeznest.com/main/tracking/courseLog.php?cid=3&gid=0)
> 
> At the bottom of that page, there is a table that shows only the users subscribed to the course. I need a button to also show the users not subscribed. The current report you have made has to change (I would remove it completely from there). Sorry for the lack of precision in my initial request.

It is checked and added with this commit https://github.com/chamilo/chamilo-lms/pull/6734/commits/dc14cca6163de571fcfb67a427901c53080833f5

Thanks for confirmation.

**Comment by ywarnier** [comment]
Almost there : you put the button in the right place, but when you press the button, the table with Name/Time/Average time in the course/Course progress/Exercise average should show those additional users with their tracking. You don't need to show a new page.

Each non-enrolled user should have a "(free)" label (in lowercase) next to their name.

When you click *again*, the table is reloaded without those users.

The title of the button should be "Show free users (not enrolled)" / "Hide free users (not enrolled)"

**Comment by christianbeeznest** [comment]
> Almost there : you put the button in the right place, but when you press the button, the table with Name/Time/Average time in the course/Course progress/Exercise average should show those additional users with their tracking. You don't need to show a new page.
> 
> Each non-enrolled user should have a "(free)" label (in lowercase) next to their name.
> 
> When you click _again_, the table is reloaded without those users.
> 
> The title of the button should be "Show free users (not enrolled)" / "Hide free users (not enrolled)"

It is checked with this commit https://github.com/christianbeeznest/chamilo-lms/commit/6f34b66f3def564fd4df51022003845c8ca5f4ef

Thanks for confirmation

**Comment by ywarnier** [comment]
Yes, that is correct. The "total" line should still be the last line (now it appears on top of the free users), but otherwise we're good.

**Comment by christianbeeznest** [comment]
It is checked with this commit https://github.com/chamilo/chamilo-lms/pull/6741/commits/ea2dd2851405e45556d68be79d08ca2e9d572e30

Thanks.

**Comment by ywarnier** [comment]
Now it's OK 😄  Thanks!

<img width="1358" height="481" alt="Image" src="https://github.com/user-attachments/assets/db9ac754-d06c-4cc1-8f77-d15d83dde03c" />
